### ISSUE TITLE
action自动签到失效是何解？只能手动运行。

### ISSUE THREAD

**Issue by Doctorlee0827** [Chasing66/smzdm_bot#10]
on:
  workflow_dispatch:

  # Uncomment below to schedule your job
   schedule:
     - cron: "0 18 * * *"
    
修改注释，cron表达式也改过，貌似都不行，是不是还需要调整代码或者设置哪里？因为以前使用过某项目的签到都能自动运行，本项目不知如何实现自动功能。

**Comment by Chasing66** [comment]
这还不清晰吗

```yaml
name: "SMZDM Check-in Bot"

on:
  workflow_dispatch:

  # Uncomment below to schedule your job
  schedule:
    - cron: "0 18 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Working
        env:
          SMZDM_COOKIE: ${{ secrets.SMZDM_COOKIE }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          SC_KEY: ${{ secrets.SC_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: python main.py
```
